<?php
$nombre = ["ANTHONY","CLEMENTE","ELDER","RICARDO","NESTOR","VANDERZAR","ISSAC","ROMARIO","JOSE",
"MAINOR","ORLANDO","CRISTIAN","WILSON","EDGARDO","EDUARDO","VICTOR","JOHAN","ORLYN","REINALDO","CARLOS","JACK",
"MAX","REX","JOSUE"];

$Snombre = ["WILSON","EDGARDO","EDUARDO","VICTOR","JOHAN","ORLYN","REINALDO","CARLOS","JACK",
"MAX","REX","JOSUE","ANTHONY","CLEMENTE","ELDER","RICARDO","NESTOR","VANDERZAR","ISSAC","ROMARIO","JOSE",
"MAINOR","ORLANDO","CRISTIAN"];

$apellido = ["OLIVA","MURILLO","JACKSON","WINSTON","ARTEAGA","ZELAYA","PASTOR","ARZU","MORENO",
"PAZ","CALDERON","PALACIOS","BLANCO","FLORES","GUTY","HERNANDEZ","WOOD","CASTILLO","MUROS","CANO","GUERRERO",
"GONZALES","DIAZ","LOZANO"];

$sapellido = ["OLIVA","MURILLO","JACKSON","WINSTON","ARTEAGA","ZELAYA","PASTOR","ARZU","MORENO",
"PAZ","CALDERON","PALACIOS","BLANCO","FLORES","GUTY","HERNANDEZ","WOOD","CASTILLO","MUROS","CANO","GUERRERO",
"GONZALES","DIAZ","LOZANO"];

?>